Repository duckduckgo/macos-browser, pull requests merged in 2024-10, with the labels that each got.

#3335 Adds new debug screen to view raw credentials data
  DuckDuckGo.xcodeproj/project.pbxproj
  DuckDuckGo/Autofill/Debug/AutofillCredentialsDebugView.swift
  DuckDuckGo/Autofill/Debug/AutofillCredentialsDebugViewModel.swift
  DuckDuckGo/DeviceAuthentication/DeviceAuthenticator.swift
  DuckDuckGo/Menus/MainMenu.swift
  DuckDuckGo/Menus/MainMenuActions.swift
Labels: stale

#3337 Check for RMF store existence inside the Task that triggers fetching
  DuckDuckGo/RemoteMessaging/RemoteMessagingClient.swift
Labels: stale

#3350 Prohibit running multiple instances of the app
  DuckDuckGo/Info.plist
Labels: merge on approve, stale

#3300 BookmarkManager minor improvements
  DuckDuckGo/Bookmarks/Model/BookmarkManager.swift
  DuckDuckGo/Bookmarks/Services/BookmarkStore.swift
  DuckDuckGo/Bookmarks/Services/BookmarkStoreMock.swift
  DuckDuckGo/Bookmarks/Services/LocalBookmarkStore.swift
  DuckDuckGo/Bookmarks/ViewModel/AddBookmarkFolderPopoverViewModel.swift
  DuckDuckGo/Bookmarks/ViewModel/AddEditBookmarkFolderDialogViewModel.swift
  DuckDuckGo/Common/Localizables/UserText.swift
  DuckDuckGo/SecureVault/Extensions/NSAlert+PasswordManager.swift
  UnitTests/Bookmarks/Model/LocalBookmarkManagerTests.swift
  UnitTests/Bookmarks/Services/LocalBookmarkStoreTests.swift
  UnitTests/HomePage/Mocks/MockBookmarkManager.swift
Labels: stale

#3241 show X on Tab when Cmd is pressed
  DuckDuckGo/TabBar/View/TabBarViewItem.swift
Labels: pending ship review, stale

#3250 Display Fire window downloads per Fire Window
  DuckDuckGo.xcodeproj/project.pbxproj
  DuckDuckGo/Application/AppDelegate.swift
  DuckDuckGo/Common/Extensions/NSAlertExtension.swift
  DuckDuckGo/Common/Extensions/NSEventExtension.swift
  DuckDuckGo/Common/Extensions/StringExtension.swift
  DuckDuckGo/Common/Localizables/UserText.swift
  DuckDuckGo/FileDownload/Model/DownloadListItem.swift
  DuckDuckGo/FileDownload/Model/DownloadListViewModel.swift
  DuckDuckGo/FileDownload/Model/FileDownloadManager.swift
  DuckDuckGo/FileDownload/Model/WebKitDownloadTask.swift
  DuckDuckGo/FileDownload/Services/DownloadListCoordinator.swift
  DuckDuckGo/FileDownload/Services/DownloadListStore.swift
  DuckDuckGo/FileDownload/View/DownloadsCellView.swift
  DuckDuckGo/FileDownload/View/DownloadsPopover.swift
  DuckDuckGo/FileDownload/View/DownloadsViewController.swift
  DuckDuckGo/FileDownload/View/NSAlert+ActiveDownloadsTermination.swift
  DuckDuckGo/Fire/Model/Fire.swift
  DuckDuckGo/Localizable.xcstrings
  DuckDuckGo/MainWindow/FireWindowSession.swift
  DuckDuckGo/MainWindow/MainWindowController.swift
  DuckDuckGo/NavigationBar/View/NavigationBarPopovers.swift
  DuckDuckGo/NavigationBar/View/NavigationBarViewController.swift
  DuckDuckGo/Tab/TabExtensions/DownloadsTabExtension.swift
  DuckDuckGo/Windows/View/WindowsManager.swift
  UnitTests/FileDownload/DownloadListCoordinatorTests.swift
  UnitTests/FileDownload/DownloadListStoreTests.swift
  UnitTests/FileDownload/FileDownloadManagerTests.swift
  UnitTests/FileDownload/Helpers/FileDownloadManagerMock.swift
  UnitTests/NavigationBar/View/NavigationBarPopoversTests.swift
Labels: pending ship review

#3356 Inspector: open link in new window
  DuckDuckGo/Tab/Model/Tab+UIDelegate.swift
  DuckDuckGo/Tab/Model/Tab.swift
  DuckDuckGo/Tab/View/WebView.swift
Labels: stale

#3389 Freemium PIR: Subscription Attribution
  DuckDuckGo/Freemium/DBP/FreemiumDBPPromotionViewCoordinator.swift
  DuckDuckGo/Subscription/SubscriptionAttributionPixelHandler.swift
  DuckDuckGo/Tab/UserScripts/Subscription/SubscriptionPagesUseSubscriptionFeature.swift
  UnitTests/Freemium/DBP/FreemiumDBPPromotionViewCoordinatorTests.swift
  UnitTests/Subscription/SubscriptionPagesUseSubscriptionFeatureTests.swift
Labels: stale

#3438 VPN logs level set as default instead of debug.
  DuckDuckGo.xcodeproj/project.pbxproj
  DuckDuckGo.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  DuckDuckGo/LoginItems/LoginItemsManager.swift
  DuckDuckGo/NetworkProtection/AppTargets/BothAppTargets/NetworkProtectionTunnelController.swift
  DuckDuckGo/NetworkProtection/NetworkExtensionTargets/NetworkExtensionTargets/MacPacketTunnelProvider.swift
  DuckDuckGo/NetworkProtection/NetworkExtensionTargets/NetworkExtensionTargets/NetworkProtectionTokenStore+SubscriptionTokenKeychainStorage.swift
  DuckDuckGoNotifications/DuckDuckGoNotificationsAppDelegate.swift
  DuckDuckGoVPN/DuckDuckGoVPNAppDelegate.swift
  LocalPackages/DataBrokerProtection/Package.swift
  LocalPackages/NetworkProtectionMac/Package.swift
  LocalPackages/SubscriptionUI/Package.swift
Labels: includes BSK changes

#3409 Add Search Bar on the New Tab Page
  DuckDuckGo.xcodeproj/project.pbxproj
  DuckDuckGo.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  DuckDuckGo/Assets.xcassets/Colors/HomePage/HomePageAddressBarBackgroundColor.colorset/Contents.json
  DuckDuckGo/Assets.xcassets/Colors/HomePage/HomePageAddressBarBorderColor.colorset/Contents.json
  DuckDuckGo/Assets.xcassets/Images/DuckDuckGoWordmark.imageset/Contents.json
  DuckDuckGo/Assets.xcassets/Images/DuckDuckGoWordmark.imageset/Wordmark.svg
  DuckDuckGo/Assets.xcassets/Images/HomePage/SettingsOnboardingPopoverImage.imageset/Contents.json
  DuckDuckGo/Assets.xcassets/Images/HomePage/SettingsOnboardingPopoverImage.imageset/Image.svg
  DuckDuckGo/Common/Localizables/UserText.swift
  DuckDuckGo/Common/Utilities/UserDefaultsWrapper.swift
  DuckDuckGo/ContentBlocker/AppPrivacyConfigurationDataProvider.swift
  DuckDuckGo/ContentBlocker/macos-config.json
  DuckDuckGo/HomePage/Model/HomePageAddressBarModel.swift
  DuckDuckGo/HomePage/Model/HomePageSettings/HomePageSettingsModel.swift
  DuckDuckGo/HomePage/Model/NewTabPageSearchBoxExperiment+Logger.swift
  DuckDuckGo/HomePage/Model/NewTabPageSearchBoxExperiment.swift
  DuckDuckGo/HomePage/View/AddressBarTextFieldView.swift
  DuckDuckGo/HomePage/View/BurnerHomePageView.swift
  DuckDuckGo/HomePage/View/FavoritesView.swift
  DuckDuckGo/HomePage/View/HomePageSettings/HomeContentSectionsView.swift
  DuckDuckGo/HomePage/View/HomePageView.swift
  DuckDuckGo/HomePage/View/HomePageViewController.swift
  DuckDuckGo/HomePage/View/MoreOrLessView.swift
  DuckDuckGo/HomePage/View/RecentlyVisitedView.swift
  DuckDuckGo/HomePage/View/RemoteMessageView.swift
  DuckDuckGo/Localizable.xcstrings
  DuckDuckGo/MainWindow/MainViewController.swift
  DuckDuckGo/MainWindow/MainWindow.swift
  DuckDuckGo/Menus/MainMenu.swift
  DuckDuckGo/Menus/MainMenuActions.swift
  DuckDuckGo/MessageViews/PopoverMessageViewController.swift
  DuckDuckGo/NavigationBar/View/AddressBarButtonsViewController.swift
  DuckDuckGo/NavigationBar/View/AddressBarTextField.swift
  DuckDuckGo/NavigationBar/View/AddressBarViewController.swift
  DuckDuckGo/NavigationBar/View/NavigationBar.storyboard
  DuckDuckGo/Preferences/Model/AppearancePreferences.swift
  DuckDuckGo/Preferences/View/PreferencesAppearanceView.swift
  DuckDuckGo/Preferences/View/PreferencesRootView.swift
  DuckDuckGo/Preferences/View/PreferencesViewController.swift
  DuckDuckGo/Statistics/GeneralPixel.swift
  DuckDuckGo/Statistics/NewTabSearchBoxExperimentPixel.swift
  DuckDuckGo/Suggestions/View/Suggestion.storyboard
  DuckDuckGo/Suggestions/View/SuggestionViewController.swift
  DuckDuckGo/Tab/View/BrowserTabViewController.swift
  LocalPackages/DataBrokerProtection/Package.swift
  LocalPackages/NetworkProtectionMac/Package.swift
  LocalPackages/SubscriptionUI/Package.swift
  LocalPackages/SwiftUIExtensions/Sources/SwiftUIExtensions/PopoverMessageView.swift
  UnitTests/HomePage/HomePageSettingsVisibilityModelTests.swift
  UnitTests/HomePage/NewTabPageSearchBoxExperimentTests.swift
  UnitTests/Preferences/AppearancePreferencesTests.swift
  UnitTests/Sync/Mocks/MockAppearancePreferencesPersistor.swift
Labels: pending ship review

#3456 Update OnboardingUserScript to use a weak script broker reference
  DuckDuckGo/Onboarding/OnboardingUserScript.swift
Labels: release branch PR

#3401 New tagline
  DuckDuckGo/Common/Localizables/UserText.swift
  DuckDuckGo/Localizable.xcstrings
  DuckDuckGo/Preferences/View/PreferencesAboutView.swift
  SyncE2EUITests/CriticalPathsTests.swift
  UITests/OnboardingUITests.swift
  UnitTests/DataImport/DataImportResources/TestBookmarksData/bookmarks_brave.html
  UnitTests/DataImport/DataImportResources/TestBookmarksData/bookmarks_chrome.html
  UnitTests/DataImport/DataImportResources/TestBookmarksData/bookmarks_ddg_android.html
  UnitTests/DataImport/DataImportResources/TestBookmarksData/bookmarks_ddg_ios.html
  UnitTests/DataImport/DataImportResources/TestBookmarksData/bookmarks_ddg_macos.html
  UnitTests/DataImport/DataImportResources/TestBookmarksData/bookmarks_firefox.html
  UnitTests/DataImport/DataImportResources/TestBookmarksData/bookmarks_safari.html
  UnitTests/DataImport/__Snapshots__/BookmarksHTMLReaderTests/snapshot.bookmarks_brave.json
  UnitTests/DataImport/__Snapshots__/BookmarksHTMLReaderTests/snapshot.bookmarks_chrome.json
  UnitTests/DataImport/__Snapshots__/BookmarksHTMLReaderTests/snapshot.bookmarks_ddg_android.json
  UnitTests/DataImport/__Snapshots__/BookmarksHTMLReaderTests/snapshot.bookmarks_ddg_ios.json
  UnitTests/DataImport/__Snapshots__/BookmarksHTMLReaderTests/snapshot.bookmarks_ddg_macos.json
  UnitTests/DataImport/__Snapshots__/BookmarksHTMLReaderTests/snapshot.bookmarks_firefox.json
  UnitTests/DataImport/__Snapshots__/BookmarksHTMLReaderTests/snapshot.bookmarks_safari.json
Labels: pending ship review
