Repository duckduckgo/macos-browser, pull requests merged in 2024-11, with the labels that each got.

#3492 Marking latest Bitwarden versions as incompatible
  DuckDuckGo/Common/Localizables/UserText.swift
  DuckDuckGo/Localizable.xcstrings
  DuckDuckGo/PasswordManager/Bitwarden/Services/BWInstallationService.swift
  DuckDuckGo/Preferences/View/PreferencesAutofillView.swift
Labels: merge on approve

#3437 Send success pixel on successful data import
  DuckDuckGo/DataImport/Bookmarks/Safari/SafariDataImporter.swift
  DuckDuckGo/DataImport/Logins/Chromium/ChromiumDataImporter.swift
  DuckDuckGo/DataImport/Logins/Firefox/FirefoxDataImporter.swift
  DuckDuckGo/DataImport/Model/DataImportViewModel.swift
  DuckDuckGo/Statistics/GeneralPixel.swift
Labels: stale

#3595 Malware protection 2: API Client refactoring
  DuckDuckGo.xcodeproj/project.pbxproj
  DuckDuckGo.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  DuckDuckGo/MaliciousSiteProtection/MaliciousSiteProtectionManager.swift
Labels: includes BSK changes

#3616 Revert to empty RMF config for debug builds
  DuckDuckGo/RemoteMessaging/RemoteMessagingClient.swift
Labels: merge on approve
