Repository duckduckgo/macos-browser, pull requests merged in 2025-01, with the labels that each got.

#3678 Convert Verecor child sites to be parent sites
  LocalPackages/DataBrokerProtection/Sources/DataBrokerProtection/Resources/JSON/backgroundcheck.run.json
  LocalPackages/DataBrokerProtection/Sources/DataBrokerProtection/Resources/JSON/clubset.com.json
  LocalPackages/DataBrokerProtection/Sources/DataBrokerProtection/Resources/JSON/councilon.com.json
  LocalPackages/DataBrokerProtection/Sources/DataBrokerProtection/Resources/JSON/curadvisor.com.json
  LocalPackages/DataBrokerProtection/Sources/DataBrokerProtection/Resources/JSON/kwold.com.json
  LocalPackages/DataBrokerProtection/Sources/DataBrokerProtection/Resources/JSON/newenglandfacts.com.json
  LocalPackages/DataBrokerProtection/Sources/DataBrokerProtection/Resources/JSON/people-background-check.com.json
  LocalPackages/DataBrokerProtection/Sources/DataBrokerProtection/Resources/JSON/vericora.com.json
  LocalPackages/DataBrokerProtection/Sources/DataBrokerProtection/Resources/JSON/veriforia.com.json
  LocalPackages/DataBrokerProtection/Sources/DataBrokerProtection/Resources/JSON/virtory.com.json
  LocalPackages/DataBrokerProtection/Sources/DataBrokerProtection/Resources/JSON/wellnut.com.json
Labels: stale

#3731 AI Chat rebranding
  DuckDuckGo/Assets.xcassets/Images/AIChat.imageset/AIChat.pdf
  DuckDuckGo/Assets.xcassets/Images/AiChatPreferences.imageset/AiChatPreferences.pdf
  DuckDuckGo/Common/Localizables/UserText.swift
  DuckDuckGo/Localizable.xcstrings
  DuckDuckGo/Preferences/View/PreferencesAIChat.swift
Labels: DO NOT MERGE

#3757 Fire Pixel on matches api request timeout
  DuckDuckGo.xcodeproj/project.pbxproj
  DuckDuckGo.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  DuckDuckGo/Common/Logger+Multiple.swift
  DuckDuckGo/MaliciousSiteProtection/MaliciousSiteProtectionManager.swift
  LocalPackages/DataBrokerProtection/Package.swift
  LocalPackages/FeatureFlags/Package.swift
  LocalPackages/NetworkProtectionMac/Package.swift
  LocalPackages/NewTabPage/Package.swift
  LocalPackages/SubscriptionUI/Package.swift
  LocalPackages/WebKitExtensions/Package.swift
Labels: includes BSK changes

#3754 Add Malicious site detection auth header
  DuckDuckGo.xcodeproj/project.pbxproj
  DuckDuckGo.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  LocalPackages/DataBrokerProtection/Package.swift
  LocalPackages/FeatureFlags/Package.swift
  LocalPackages/NetworkProtectionMac/Package.swift
  LocalPackages/NewTabPage/Package.swift
  LocalPackages/SubscriptionUI/Package.swift
  LocalPackages/WebKitExtensions/Package.swift
Labels: includes BSK changes

#3761 Malicious Site Protection activatable by subfeature
  DuckDuckGo.xcodeproj/project.pbxproj
  DuckDuckGo.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  DuckDuckGo/ContentBlocker/AppPrivacyConfigurationDataProvider.swift
  DuckDuckGo/ContentBlocker/macos-config.json
  DuckDuckGo/MaliciousSiteProtection/MaliciousSiteProtectionManager.swift
  DuckDuckGo/Preferences/View/PreferencesGeneralView.swift
  IntegrationTests/MaliciousSiteProtection/MaliciousSiteProtectionIntegrationTests.swift
  LocalPackages/DataBrokerProtection/Package.swift
  LocalPackages/FeatureFlags/Package.swift
  LocalPackages/FeatureFlags/Sources/FeatureFlags/FeatureFlag.swift
  LocalPackages/HistoryView/Package.swift
  LocalPackages/NetworkProtectionMac/Package.swift
  LocalPackages/NewTabPage/Package.swift
  LocalPackages/SubscriptionUI/Package.swift
  LocalPackages/UserScriptActionsManager/Package.swift
  LocalPackages/WebKitExtensions/Package.swift
  UnitTests/MaliciousSiteProtection/MaliciousSiteProtectionTests.swift
Labels: includes BSK changes

#3772 Fix Malsite protection tests failing; fix matches api timeout Pixel name
  DuckDuckGo.xcodeproj/project.pbxproj
  DuckDuckGo.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  DuckDuckGo/MaliciousSiteProtection/MaliciousSiteProtectionManager.swift
  DuckDuckGo/Tab/TabExtensions/DuckPlayerTabExtension.swift
  IntegrationTests/MaliciousSiteProtection/MaliciousSiteProtectionIntegrationTests.swift
  IntegrationTests/MaliciousSiteProtection/match.api.response.json
  LocalPackages/DataBrokerProtection/Package.swift
  LocalPackages/FeatureFlags/Package.swift
  LocalPackages/HistoryView/Package.swift
  LocalPackages/NetworkProtectionMac/Package.swift
  LocalPackages/NewTabPage/Package.swift
  LocalPackages/SubscriptionUI/Package.swift
  LocalPackages/UserScriptActionsManager/Package.swift
  LocalPackages/WebKitExtensions/Package.swift
Labels: includes BSK changes

#3746 Authv2 / Networking improvements
  DuckDuckGo-macOS.xcodeproj/project.pbxproj
  DuckDuckGo-macOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  DuckDuckGo/NetworkProtection/AppAndExtensionTargets/AppAndExtensionAndNotificationTargets/Bundle+VPN.swift
  DuckDuckGo/NetworkProtection/AppTargets/BothAppTargets/KeychainType+ClientDefault.swift
  DuckDuckGo/NetworkProtection/AppTargets/DeveloperIDTarget/NetworkProtectionSubscriptionEventHandler.swift
  DuckDuckGo/UnifiedFeedbackForm/UnifiedFeedbackFormViewModel.swift
  LocalPackages/DataBrokerProtection/Package.swift
  LocalPackages/FeatureFlags/Package.swift
  LocalPackages/HistoryView/Package.swift
  LocalPackages/NetworkProtectionMac/Package.swift
  LocalPackages/NewTabPage/Package.swift
  LocalPackages/NewTabPage/Sources/NewTabPage/Favorites/NewTabPageDataModel+Favorites.swift
  LocalPackages/NewTabPage/Tests/NewTabPageTests/NewTabPageFavoritesClientTests.swift
  LocalPackages/NewTabPage/Tests/NewTabPageTests/NewTabPageFavoritesModelTests.swift
  LocalPackages/NewTabPage/Tests/NewTabPageTests/NewTabPageNextStepsCardsClientTests.swift
  LocalPackages/NewTabPage/Tests/NewTabPageTests/NewTabPagePrivacyStatsClientTests.swift
  LocalPackages/NewTabPage/Tests/NewTabPageTests/NewTabPagePrivacyStatsModelTests.swift
  LocalPackages/SubscriptionUI/Package.swift
  LocalPackages/UserScriptActionsManager/Package.swift
  LocalPackages/WebKitExtensions/Package.swift
  UnitTests/MaliciousSiteProtection/MaliciousSiteProtectionTests.swift
  UnitTests/Subscription/SubscriptionPagesUseSubscriptionFeatureTests.swift
  UnitTests/Sync/Mocks/MockDDGSyncing.swift
  UnitTests/Sync/SyncPreferencesTests.swift
  UnitTests/UnifiedFeedbackForm/UnifiedFeedbackFormViewModelTests.swift
Labels: includes BSK changes, DO NOT MERGE

#3776 Apple ID > Apple Account
  DuckDuckGo/Localizable.xcstrings
  LocalPackages/SubscriptionUI/Sources/SubscriptionUI/Resources/Localizable.xcstrings
  LocalPackages/SubscriptionUI/Sources/SubscriptionUI/UserText.swift
Labels: DO NOT MERGE
